### ISSUE TITLE
bug: error while merging with empty target element

### ISSUE THREAD

**Issue by Darkein** [jaroslavsvak/xlf-merge#3]
Hey!

I got an error when i'm trying to merge files with empty target element (because it's not translated yet)

```batch
Error: Cannot read property 'find' of undefined
    at getContent (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\merge-xlf.js:32:13)
    at module.exports (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\merge-xlf.js:61:21)
    at runMerge (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\index.js:19:18)
    at Object.<anonymous> (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\index.js:41:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

I think you just have to return an empty string if your element doesn't have element (elements attribute is null).

thanks !

**Comment by headhunter45** [comment]
I needed this to merge untranslated files.  In my case these were extracted xlfs from different branches of an angular app.
