### ISSUE TITLE
Allow merge files when an ID is duplicate

### ISSUE THREAD

**Issue by xavadu** [jaroslavsvak/xlf-merge#7]
Feature request :)

I am using your tool with Angular to merge the translation from the templates generated from `ng xi18n` with the translation generated from the code with `locl`[1] and later run `xliffmerge`[2][3] to generate all the other languages translation file meanwhile doing a merge.

It happen that for few translation I have the ID defines in the code with `$localize` and in the template with the directive `i18n`, when I try to merge two files with this tool and the ID exists in both, we get this error message:

```
Initial file src/translations/messages-template.xlf
trans-unit sections/navbar.brand
already present content: 
differs in file src/translations/messages-code.xlf : BRAND-NAME
Error: Translations mismatch at trans-unit ID: sections/navbar.brand. File name: src/translations/messages-code.xlf.
    at fail (/var/www/node_modules/xlf-merge/merge-xlf.js:3:15)
    at module.exports (/var/www/node_modules/xlf-merge/merge-xlf.js:73:17)
    at runMerge (/var/www/node_modules/xlf-merge/index.js:19:18)
    at Object.<anonymous> (/var/www/node_modules/xlf-merge/index.js:41:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

It would be great if is possible to set a precedence to override one ID with another, or only throw error or better a warning, if ID are equal but translation different. 

Thanks

[1] https://github.com/loclapp/locl/tree/master/libs/cli
[2] https://github.com/martinroob/ngx-i18nsupport/tree/master/projects/xliffmerge
[3] https://github.com/martinroob/ngx-i18nsupport/wiki/Tutorial-for-using-xliffmerge-with-angular-cli

**Comment by kaylucas** [comment]
I ran into the same problem, so I forked the repository to make it do exactly what I want it to: always prioritise the target translation over the original content. You can try that one here: https://github.com/kaylucas/xlf-merge

Someone else also changed some things around and created a version that only fails when the translation is not empty:
https://github.com/breningham/xlf-merge. That one has a pull request here but it's unfortunately not accepted yet.

Depending on your needs you can try one of those, hopefully it solves your problem too!

**Comment by xavadu** [comment]
@kaylucas thanks for you reply and solution

**Comment by jaroslavsvak** [comment]
Added parameter --allow-conflicts, which doesn't treat duplicates as error
